name: Example PR Comment

on:
  pull_request:
 
jobs:
 example_comment_pr: 
  permissions: write-all
  runs-on: ubuntu-latest 
  name: An example job to comment a PR
  steps:
   - name: Checkout
     uses: actions/checkout@v3
     
   - name: Comment PR
     uses: thollander/actions-comment-pull-request@v1
     with: 
       message: "I appreciate your updates! :wave:"
       reactions: eyes, rocket

       token: ${{ secrets.GITHUB_TOKEN }}
